name: ui_tool
description: Make the widgets more responsive
version: 0.0.1
homepage: https://github.com/kasun-u/ui_tool

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

repository: https://github.com/kasun-u/ui_tool

flutter:
